### PR TITLE
Mailing fix

### PR DESCRIPTION
**Pull request by ghost**
Now it should work

### CODE REVIEW

**Review by ekanime — COMMENTED** [review]
still doesn't work I am getting a 405 error

**Comment by gold604** [comment]
Your webserver is misconfigured. I guess you've uploaded your website on some webhosting, right? Can you place .htaccess file within your root directory with content: 
`<Limit GET POST>
Require all granted
</Limit>`

**Comment by ghost** [comment]
It has to be something with your webserver configuration. I can't reproduce your error

**Comment by ekanime** [comment]
|I use Google chrome but I tried to run it on safari and it still didn't work

**Pull request merged**
